"""Local python-pptx stub deck when DeepPresenter is unavailable."""

from __future__ import annotations

import io
import re
from typing import Any

from pptx import Presentation
from pptx.util import Inches, Pt


def _slides_from_query(query: str, *, max_slides: int = 6) -> list[tuple[str, list[str]]]:
    text = re.sub(r"\s+", " ", (query or "").strip())
    title = text[:60] + ("…" if len(text) > 60 else "") or "Untitled deck"
    bullets = [
        "Generated by AOP ppt-agent stub (python-pptx).",
        "Enable DeepPresenter Docker for reflective PPTAgent quality.",
        f"Prompt: {text[:200]}" + ("…" if len(text) > 200 else ""),
    ]
    outline: list[tuple[str, list[str]]] = [
        (title, bullets),
        ("Agenda", ["Background", "Key points", "Next steps"]),
        ("Background", ["Context from the task prompt", "Upstream research may refine this"]),
        ("Key points", ["Point A", "Point B", "Point C"]),
        ("Recommendations", ["Adopt agentic PPT when Docker is ready", "Keep stub for local demos"]),
        ("Summary", ["Stub PPTX is editable", "Swap backend via PPT_MODE"]),
    ]
    return outline[: max(1, max_slides)]


def build_stub_pptx(query: str, *, max_slides: int = 6) -> tuple[bytes, dict[str, Any]]:
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]
    slides = _slides_from_query(query, max_slides=max_slides)

    for i, (heading, bullets) in enumerate(slides):
        slide = prs.slides.add_slide(blank)
        title_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.4), Inches(12), Inches(1))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = heading
        p.font.size = Pt(32 if i == 0 else 28)
        p.font.bold = True

        body = slide.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.5), Inches(5))
        btf = body.text_frame
        btf.clear()
        for j, line in enumerate(bullets):
            para = btf.paragraphs[0] if j == 0 else btf.add_paragraph()
            para.text = line
            para.font.size = Pt(18)
            para.level = 0

    buf = io.BytesIO()
    prs.save(buf)
    raw = buf.getvalue()
    meta = {
        "source": "stub",
        "slide_count": len(slides),
        "format": "pptx",
        "note": "Stub python-pptx deck. Set PPT_MODE=deeppresenter when aop-deeppresenter is running.",
    }
    return raw, meta
