import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ensureDir, pathExists, readText, writeText } from "../tools/filesystem.js";
import { mirrorLibraryImage } from "../tools/image-resolve.js";
import type { DeployPlan, ProjectInfo } from "../types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

export function packageRoot(): string {
  return join(__dirname, "..", "..");
}

export function templatesDir(): string {
  return join(packageRoot(), "templates", "docker-compose");
}

export function skillsDir(): string {
  return join(packageRoot(), "skills");
}

function javaImageTag(version?: string): string {
  const v = (version || "17").replace(/[^0-9]/g, "") || "17";
  const major = ["8", "11", "17", "21"].includes(v) ? v : "17";
  return major;
}

export function ensureGeneratedDockerfile(project: ProjectInfo): string | undefined {
  if (project.hasDockerfile) return "Dockerfile";
  if (project.hasCompose && project.kind !== "java") return undefined;

  const port =
    project.ports[0] ??
    (project.kind === "python" ? 8000 : project.kind === "java" ? 8080 : 3000);
  let content = "";

  if (project.kind === "nodejs") {
    const pm = project.packageManager ?? "npm";
    const install =
      pm === "pnpm"
        ? "npm i -g pnpm && pnpm install --frozen-lockfile || pnpm install"
        : pm === "yarn"
          ? "yarn install --frozen-lockfile || yarn install"
          : pm === "bun"
            ? "npm i -g bun && bun install"
            : "npm ci || npm install";
    const start = project.node?.scripts?.start
      ? pm === "npm"
        ? "npm start"
        : `${pm} start`
      : project.node?.scripts?.dev
        ? pm === "npm"
          ? "npm run dev -- --host 0.0.0.0 --port " + port
          : `${pm} run dev`
        : "node index.js";
    const nodeImage = mirrorLibraryImage("node:20-alpine");

    content = `FROM ${nodeImage}
WORKDIR /app
COPY package*.json ./
COPY pnpm-lock.yaml* yarn.lock* bun.lockb* bun.lock* ./
RUN ${install}
COPY . .
ENV PORT=${port}
ENV HOST=0.0.0.0
EXPOSE ${port}
CMD ${JSON.stringify(start.split(/\s+/))}
`;
  } else if (project.kind === "python") {
    const hasReq = pathExists(join(project.root, "requirements.txt"));
    const cmd = project.frameworks.includes("uvicorn")
      ? `["uvicorn","main:app","--host","0.0.0.0","--port","${port}"]`
      : project.entrypoints[0]?.startsWith("python ")
        ? JSON.stringify(project.entrypoints[0].split(/\s+/))
        : `["python","-m","http.server","${port}"]`;
    const pyImage = mirrorLibraryImage("python:3.12-slim");

    content = `FROM ${pyImage}
WORKDIR /app
COPY . .
${hasReq ? "RUN pip install --no-cache-dir -r requirements.txt" : "RUN pip install --no-cache-dir fastapi uvicorn flask django || true"}
ENV PORT=${port}
EXPOSE ${port}
CMD ${cmd}
`;
  } else if (project.kind === "java") {
    const jv = javaImageTag(project.java?.javaVersion);
    const module = project.java?.serverModule;
    const buildCmd = module
      ? `mvn -B -pl ${module} -am package -DskipTests`
      : "mvn -B package -DskipTests";
    const mavenImage = mirrorLibraryImage(`maven:3.9-eclipse-temurin-${jv}`);
    const jreImage = mirrorLibraryImage(`eclipse-temurin:${jv}-jre`);

    content = `# Generated by DeployPilot for Maven/Spring Boot
FROM ${mavenImage} AS build
WORKDIR /src
COPY . .
RUN ${buildCmd} \\
 && mkdir -p /out \\
 && sh -c 'jar=$(ls ${module ? `${module}/` : ""}target/*.jar 2>/dev/null | grep -v plain | head -n1) && cp "$$jar" /out/app.jar'

FROM ${jreImage}
WORKDIR /app
COPY --from=build /out/app.jar /app/app.jar
ENV SERVER_PORT=${port}
EXPOSE ${port}
ENTRYPOINT ["java","-jar","/app/app.jar"]
`;
  } else {
    return undefined;
  }

  writeText(join(project.root, "Dockerfile"), content);
  writeText(
    join(project.root, ".deploypilot-generated"),
    "Dockerfile generated by DeployPilot\n",
  );
  return "Dockerfile";
}

export function ensureGeneratedCompose(
  project: ProjectInfo,
  plan: DeployPlan,
): string | undefined {
  if (
    project.hasCompose &&
    project.composeFile &&
    !pathExists(join(project.root, ".deploypilot-generated-compose"))
  ) {
    return project.composeFile;
  }
  if (plan.runtime !== "docker-compose") return undefined;
  if (project.kind !== "java") return undefined;

  const port = plan.healthPort ?? project.ports[0] ?? 8080;
  const imageTag = plan.imageTag;
  const needsMysql = project.java?.needsMysql !== false;
  const needsRedis = Boolean(project.java?.needsRedis);
  const mysqlImage = mirrorLibraryImage("mysql:8.0");
  const redisImage = "redis:7-alpine";

  const services: string[] = [];

  if (needsMysql) {
    services.push(`  mysql:
    image: ${mysqlImage}
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: sky_take_out
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20
    mem_limit: 512m
`);
  }

  if (needsRedis) {
    services.push(`  redis:
    image: ${redisImage}
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    mem_limit: 256m
`);
  }

  const dependsOn: string[] = [];
  if (needsMysql) {
    dependsOn.push(`      mysql:
        condition: service_healthy`);
  }
  if (needsRedis) {
    dependsOn.push(`      redis:
        condition: service_healthy`);
  }

  services.push(`  app:
    build: .
    image: ${imageTag}
    ports:
      - "${port}:${port}"
    environment:
      SERVER_PORT: "${port}"
      SKY_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SKY_DATASOURCE_HOST: mysql
      SKY_DATASOURCE_PORT: "3306"
      SKY_DATASOURCE_DATABASE: sky_take_out
      SKY_DATASOURCE_USERNAME: root
      SKY_DATASOURCE_PASSWORD: "123456"
      SKY_REDIS_HOST: redis
      SKY_REDIS_PORT: "6379"
      SKY_REDIS_PASSWORD: ""
      SKY_REDIS_DATABASE: "0"
    ${dependsOn.length ? `depends_on:\n${dependsOn.join("\n")}` : ""}
    mem_limit: 768m
    cpus: 1.0
    pids_limit: 256
`);

  const compose = `services:
${services.join("\n")}`;

  const composeFile = "docker-compose.yml";
  writeText(join(project.root, composeFile), compose);
  writeText(
    join(project.root, ".deploypilot-generated-compose"),
    "docker-compose.yml generated by DeployPilot\n",
  );
  return composeFile;
}

/** Rewrite docker.io library images in a compose file to DaoCloud mirror. */
export function rewriteComposeImagesToMirror(composePath: string): boolean {
  if (!pathExists(composePath)) return false;
  const original = readText(composePath);
  const next = original.replace(
    /(image:\s*)(?!docker\.m\.daocloud\.io\/)(mysql|redis|postgres|mongo|nginx|eclipse-temurin|maven|node|python)(:[^\s]+)?/g,
    (_m, prefix: string, name: string, tag = "") =>
      `${prefix}${mirrorLibraryImage(`${name}${tag || ""}`)}`,
  );
  if (next === original) return false;
  writeText(composePath, next);
  return true;
}

export function ensureWorkspaceLayout(workspaceDir: string): {
  sourceDir: string;
  artifactsDir: string;
} {
  const sourceDir = join(workspaceDir, "src");
  const artifactsDir = join(workspaceDir, "artifacts");
  ensureDir(sourceDir);
  ensureDir(artifactsDir);
  return { sourceDir, artifactsDir };
}

export function readTemplate(name: string): string {
  return readText(join(templatesDir(), name));
}
